// Real book glosses (Slice 1A card): word -> a plain-language-normalized
// definition, generated by `data/pipeline/glosses.py` (Wiktionary via
// wiktextract, CC BY-SA 4.0/GFDL) and narrowed to one book's own vocabulary
// -- content/glosses/<bookId>.json. See that directory's own note on what
// "normalized" does and does not mean yet: mechanical cleanup only
// (capitalization, a closing period), not the semantic plain-language
// rewrite or the ADR-012 thorny-case panel review a reader-facing gloss
// table is meant to pass before it ships widely. Attribution lives in
// Settings -> About (ADR-008).
//
// Deliberately not `fixtures/glosses.ts`'s `glossFor` -- that one is the
// hand-written curated coverage for the composed-passage reading loop,
// and this slice does not touch that loop at all
// (ADR-031: book encounters are a separate, unscheduled path). Keeping this
// a separate module means neither reading surface can accidentally read the
// other's data by a stray import.

const CONTENT_CACHE = "superb-content-v1";
const contentUrl = (name: string) => `${import.meta.env.BASE_URL}content/${name}`;

/** One tagged sense: a content part of speech ("noun" | "verb" | "adj" |
 *  "adv") and the definition that reading carries. `cap` marks a sense
 *  that lives under the capitalized headword — "English" the language
 *  against "english" the billiards spin. */
export interface GlossSense {
  pos: string;
  def: string;
  cap?: boolean;
}

export interface BookGlossEntry {
  definition: string;
  /** Present only when the word genuinely reads more than one way; the
   *  card picks against the sentence (content/senses.ts). */
  senses?: GlossSense[];
}

const tables = new Map<string, Record<string, BookGlossEntry>>();
const failures = new Map<string, Error>();

async function fetchJson<T>(url: string): Promise<T> {
  if (!("caches" in window)) return fetch(url).then((r) => r.json() as Promise<T>);

  const cache = await caches.open(CONTENT_CACHE);
  try {
    const response = await fetch(url);
    if (!response.ok) throw new Error(`${url} responded ${response.status}`);
    await cache.put(url, response.clone());
    return (await response.json()) as T;
  } catch (networkError) {
    const cached = await cache.match(url);
    if (cached) return (await cached.json()) as T;
    throw networkError;
  }
}

export async function loadBookGlosses(bookId: string): Promise<Record<string, BookGlossEntry>> {
  const cached = tables.get(bookId);
  if (cached) return cached;
  const failed = failures.get(bookId);
  if (failed) throw failed;
  try {
    const table = await fetchJson<Record<string, BookGlossEntry>>(contentUrl(`glosses/${bookId}.json`));
    tables.set(bookId, table);
    return table;
  } catch (err) {
    const error = err instanceof Error ? err : new Error(String(err));
    failures.set(bookId, error);
    throw error;
  }
}

export function resetBookGlosses(bookId: string): void {
  tables.delete(bookId);
  failures.delete(bookId);
}

/** The games' own gloss table -- every prompt, rhyme and associate word in
 *  one file, so an end-of-round reveal can say what a word means and let
 *  the reader keep it. */
export async function loadChallengeGlosses(): Promise<Record<string, BookGlossEntry>> {
  const key = "__challenges__";
  const cached = tables.get(key);
  if (cached) return cached;
  const table = await fetchJson<Record<string, BookGlossEntry>>(
    contentUrl("challenges/glosses.json"),
  );
  tables.set(key, table);
  return table;
}

/** The composed-prose table: the slot lexicon and the corpus's target
 *  words, for the word card inside the prose game. */
export async function loadProseGlosses(): Promise<Record<string, BookGlossEntry>> {
  const key = "__prose__";
  const cached = tables.get(key);
  if (cached) return cached;
  const table = await fetchJson<Record<string, BookGlossEntry>>(contentUrl("glosses/prose.json"));
  tables.set(key, table);
  return table;
}

let sharedSenses: Record<string, GlossSense[]> | null = null;
let sharedSensesFailed = false;

/** The one shared sense table (content/glosses/senses.json): tagged sense
 *  lists for every common word that genuinely reads more than one way.
 *  Every word card reads it beside its own single-definition table, so a
 *  book table stays small while "sounded" can still resolve against its
 *  sentence. A failed fetch degrades to default definitions, once. */
export async function loadSharedSenses(): Promise<Record<string, GlossSense[]>> {
  if (sharedSenses) return sharedSenses;
  if (sharedSensesFailed) return {};
  try {
    sharedSenses = await fetchJson<Record<string, GlossSense[]>>(contentUrl("glosses/senses.json"));
    return sharedSenses;
  } catch {
    sharedSensesFailed = true;
    return {};
  }
}

/** A word this table has no curated entry for is real and expected --
 *  `data/pipeline/glosses.py` only resolves the top 30,000 frequency band,
 *  so proper nouns (Harker, Transylvania) and the rarer end of Victorian
 *  prose fall outside it. Honest about that rather than inventing a
 *  definition or borrowing the older mock's "not curated for this build"
 *  wording, which described a placeholder that does not exist here -- this
 *  word plainly has no entry, and may never get one from this pipeline. */
export function glossFor(table: Record<string, BookGlossEntry>, word: string): BookGlossEntry {
  const found = table[word.toLowerCase()];
  if (found) return found;
  return { definition: "This word doesn't have a meaning saved yet." };
}
