// Bundles content/passages/*.json, content/sources/*.json, and
// content/classes/*.json (owned by T3, one level up from this repo's apps/)
// into arrays this app can fetch as static assets. Read-only against
// content/ -- never writes there.
//
// classes.json is the lexicon docs/seams.md's ContentFrame.wordClasses
// promises ("straight from the lexicon"): the real composer needs it to fill
// a composed template's slots at all (src/composer.rs::fill_slots), so this
// was already load-bearing the day the mock engine stopped standing in for
// that logic -- it just had nowhere to be fetched from until now.
//
// Regenerated before every dev server start and every build; its output
// (public/content/) is gitignored so there is exactly one copy of the
// content on disk that anyone has to keep in sync.
// difficulty.json is the word-to-θ mapping (ADR-029), generated by
// data/pipeline/difficulty.py and committed. It is what lets the content
// store answer the engine's [bandLow, bandHigh] window with words that
// actually sit inside it, instead of handing back the whole lexicon.
import { readdirSync, readFileSync, mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createHash } from "node:crypto";

const here = dirname(fileURLToPath(import.meta.url));
const contentRoot = join(here, "..", "..", "..", "content");
const outDir = join(here, "..", "public", "content");

function loadJsonDir(sub) {
  const dir = join(contentRoot, sub);
  const rows = [];
  for (const name of readdirSync(dir).sort()) {
    if (!name.endsWith(".json")) continue; // skips _seed.py
    rows.push(JSON.parse(readFileSync(join(dir, name), "utf-8")));
  }
  return rows;
}

const passages = loadJsonDir("passages");
const sources = loadJsonDir("sources");
const classes = loadJsonDir("classes");
const difficulty = JSON.parse(readFileSync(join(contentRoot, "difficulty.json"), "utf-8"));

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "passages.json"), JSON.stringify(passages));
writeFileSync(join(outDir, "sources.json"), JSON.stringify(sources));
writeFileSync(join(outDir, "classes.json"), JSON.stringify(classes));
writeFileSync(join(outDir, "difficulty.json"), JSON.stringify(difficulty));

console.log(
  `synced ${passages.length} passages, ${sources.length} sources, ${classes.length} classes, ` +
    `${Object.keys(difficulty.words).length} word difficulties -> public/content/`,
);

// Slice 1A: the catalogue artifact (content/catalogue.lock.json,
// superb-catalogue/library's scripts/export_catalogue.py) and its
// book-scoped gloss table. Both are read byte-for-byte from content/ and
// re-hashed here rather than trusted -- the lock file is the one place this
// build states what it expects to ship, so a content/catalogue/ edit that
// drifts from it fails the build instead of silently shipping the wrong
// bytes (the same freshness-gate shape every other check in this script's
// build already takes for granted, just not yet written down for this one).
const lock = JSON.parse(readFileSync(join(contentRoot, "catalogue.lock.json"), "utf-8"));
const cataloguePath = join(contentRoot, lock.vendored_path.replace(/^content\//, ""));
if (!existsSync(cataloguePath)) {
  throw new Error(`catalogue.lock.json names ${lock.vendored_path}, which does not exist`);
}
const catalogueBytes = readFileSync(cataloguePath);
const catalogueDigest = createHash("sha256").update(catalogueBytes).digest("hex");
if (catalogueDigest !== lock.sha256) {
  throw new Error(
    `content/catalogue.lock.json's sha256 (${lock.sha256}) does not match ${lock.vendored_path} (${catalogueDigest})`,
  );
}
writeFileSync(join(outDir, "catalogue-v0.1.0.json"), catalogueBytes);

const glossesDir = join(contentRoot, "glosses");
let glossFileCount = 0;
if (existsSync(glossesDir)) {
  mkdirSync(join(outDir, "glosses"), { recursive: true });
  for (const name of readdirSync(glossesDir)) {
    if (!name.endsWith(".json")) continue;
    writeFileSync(join(outDir, "glosses", name), readFileSync(join(glossesDir, name)));
    glossFileCount += 1;
  }
}

console.log(
  `synced catalogue-v0.1.0.json (${catalogueBytes.length} bytes, checksum verified) and ` +
    `${glossFileCount} book gloss table(s) -> public/content/`,
);

// The games' own data: rhyme prompts and pronunciations, association
// prompts and the answer index. Copied whole, like the gloss tables.
const challengesDir = join(contentRoot, "challenges");
let challengeFileCount = 0;
if (existsSync(challengesDir)) {
  mkdirSync(join(outDir, "challenges"), { recursive: true });
  for (const name of readdirSync(challengesDir)) {
    if (!name.endsWith(".json")) continue;
    writeFileSync(join(outDir, "challenges", name), readFileSync(join(challengesDir, name)));
    challengeFileCount += 1;
  }
}

// The full library index (one row per book), when it has been generated.
const indexPath = join(contentRoot, "catalogue", "index-v1.json");
if (existsSync(indexPath)) {
  writeFileSync(join(outDir, "catalogue-index.json"), readFileSync(indexPath));
}

console.log(`synced ${challengeFileCount} challenge data file(s) -> public/content/`);
