// Turns design/tokens.json into src/design/tokens.css -- the one file both
// registers are consumed from (ADR-019 Decision 4). One generator instead
// of hand-duplicating the same hex values in two places, which is exactly
// the kind of drift ADR-019 names as the seam's real cost.
//
// Two tiers of custom property: raw tokens (the JSON's own values, kept
// under --raw-*) and semantic tokens (--page-*, --chrome-*) that each
// register + colour-scheme combination aliases to a raw one. Components
// only ever read the semantic layer.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = join(here, "..", "..", "..", "design", "tokens.json");
const outPath = join(here, "..", "src", "design", "tokens.css");

const tokens = JSON.parse(readFileSync(tokensPath, "utf-8"));

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function rawBlock(prefix, obj) {
  return Object.entries(obj)
    .filter(([k]) => k !== "_comment")
    .map(([k, v]) => `  --raw-${prefix}-${kebab(k)}: ${v};`)
    .join("\n");
}

const lines = [];
lines.push("/* Generated by scripts/tokens-to-css.mjs from design/tokens.json. */");
lines.push("/* Do not hand-edit -- edit the JSON and regenerate. */");
lines.push("");
lines.push(":root {");
lines.push(`  --font-serif: ${tokens.font.serif};`);
lines.push(`  --font-sans: ${tokens.font.sans};`);
lines.push(`  --font-mono: ${tokens.font.mono};`);
lines.push("");
lines.push(`  --type-passage-measure: ${tokens.type.passage.measureCh}ch;`);
lines.push(`  --type-passage-line-height: ${tokens.type.passage.lineHeight};`);
lines.push(`  --type-passage-size: ${tokens.type.passage.fontSize};`);
lines.push(`  --type-passage-paragraph-spacing: ${tokens.type.passage.paragraphSpacing};`);
lines.push(`  --type-passage-letter-spacing: ${tokens.type.passage.letterSpacing};`);
for (const [k, v] of Object.entries(tokens.type.ui)) {
  lines.push(`  --type-ui-${kebab(k)}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.space)) {
  lines.push(`  --space-${k}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${kebab(k)}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.motion)) {
  lines.push(`  --motion-${kebab(k)}: ${v};`);
}
lines.push("");
lines.push(rawBlock("page-light", tokens.page.light));
lines.push(rawBlock("page-dark", tokens.page.dark));
lines.push(rawBlock("glass-dark", tokens.registers.glass.dark));
lines.push(rawBlock("glass-light", tokens.registers.glass.light));
lines.push("}");
lines.push("");

lines.push("/* Paper register (variant B): chrome recedes, --chrome-* mirrors --page-*. */");
lines.push('[data-register="paper"] {');
for (const k of Object.keys(tokens.page.light)) {
  const prop = `--page-${kebab(k)}`;
  lines.push(`  ${prop}: var(--raw-page-light-${kebab(k)});`);
  lines.push(`  --chrome-${kebab(k)}: var(${prop});`);
}
lines.push("}");
lines.push("@media (prefers-color-scheme: dark) {");
lines.push('  [data-register="paper"] {');
for (const k of Object.keys(tokens.page.dark)) {
  const prop = `--page-${kebab(k)}`;
  lines.push(`    ${prop}: var(--raw-page-dark-${kebab(k)});`);
  lines.push(`    --chrome-${kebab(k)}: var(${prop});`);
}
lines.push("  }");
lines.push("}");
lines.push("");

lines.push("/* Glass register (variant A): the card is always the warm paper-light");
lines.push("   surface -- a lit page, not an inverted one -- while the surrounding");
lines.push("   ground answers to the system's dark/light preference, dark-first. */");
lines.push('[data-register="glass"] {');
for (const k of Object.keys(tokens.page.light)) {
  lines.push(`  --page-${kebab(k)}: var(--raw-page-light-${kebab(k)});`);
}
for (const k of Object.keys(tokens.registers.glass.dark)) {
  lines.push(`  --chrome-${kebab(k)}: var(--raw-glass-dark-${kebab(k)});`);
}
lines.push("}");
lines.push("@media (prefers-color-scheme: light) {");
lines.push('  [data-register="glass"] {');
for (const k of Object.keys(tokens.registers.glass.light)) {
  lines.push(`    --chrome-${kebab(k)}: var(--raw-glass-light-${kebab(k)});`);
}
lines.push("  }");
lines.push("}");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`tokens -> ${outPath}`);
