// Turns design/tokens.json into src/design/tokens.css -- the one file the
// surface is consumed from (ADR-019 D4). One generator instead of
// hand-duplicating the same hex values in two places, which is exactly the
// kind of drift ADR-019 names as its real cost.
//
// Two tiers of custom property: raw tokens (the JSON's own values, kept
// under --raw-*) and semantic tokens (--page-*, --chrome-*) that components
// actually read. There is one register now (ADVISORY-008 §1 corrected the
// picker that asked a settled question), so unlike the generator's first
// draft there is no [data-register] attribute anywhere below -- --chrome-*
// simply answers the system's colour-scheme preference, dark-first, and
// --page-* is a fixed alias to page.light: the reading card is always a lit
// page, dark mode changes the room around it, not the page itself
// (superb-craft/reading-surface.md, "the layout does not change; the lamp
// does").
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = join(here, "..", "..", "..", "design", "tokens.json");
const outPath = join(here, "..", "src", "design", "tokens.css");

const tokens = JSON.parse(readFileSync(tokensPath, "utf-8"));

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function rawBlock(prefix, obj) {
  return Object.entries(obj)
    .filter(([k]) => k !== "_comment")
    .map(([k, v]) => `  --raw-${prefix}-${kebab(k)}: ${v};`)
    .join("\n");
}

function aliasBlock(varPrefix, rawPrefix, obj, indent = "  ") {
  return Object.keys(obj)
    .filter((k) => k !== "_comment")
    .map((k) => `${indent}--${varPrefix}-${kebab(k)}: var(--raw-${rawPrefix}-${kebab(k)});`)
    .join("\n");
}

const lines = [];
lines.push("/* Generated by scripts/tokens-to-css.mjs from design/tokens.json. */");
lines.push("/* Do not hand-edit -- edit the JSON and regenerate. */");
lines.push("");
lines.push(":root {");
lines.push(`  --font-serif: ${tokens.font.serif};`);
lines.push(`  --font-sans: ${tokens.font.sans};`);
lines.push(`  --font-mono: ${tokens.font.mono};`);
lines.push("");
lines.push(`  --type-passage-measure: ${tokens.type.passage.measureCh}ch;`);
lines.push(`  --type-passage-line-height: ${tokens.type.passage.lineHeight};`);
lines.push(`  --type-passage-size: ${tokens.type.passage.fontSize};`);
lines.push(`  --type-passage-paragraph-spacing: ${tokens.type.passage.paragraphSpacing};`);
lines.push(`  --type-passage-letter-spacing: ${tokens.type.passage.letterSpacing};`);
for (const [k, v] of Object.entries(tokens.type.ui)) {
  lines.push(`  --type-ui-${kebab(k)}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.space)) {
  lines.push(`  --space-${k}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.radius)) {
  lines.push(`  --radius-${kebab(k)}: ${v};`);
}
lines.push("");
for (const [k, v] of Object.entries(tokens.motion)) {
  lines.push(`  --motion-${kebab(k)}: ${v};`);
}
lines.push("");
lines.push(rawBlock("page-light", tokens.page.light));
lines.push(rawBlock("page-dark", tokens.page.dark));
lines.push(rawBlock("chrome-dark", tokens.chrome.dark));
lines.push(rawBlock("chrome-light", tokens.chrome.light));
lines.push("");
lines.push("  /* The reading card is always a lit page -- see the file header. */");
lines.push(aliasBlock("page", "page-light", tokens.page.light));
lines.push("");
lines.push("  /* Dark-first: the room the page floats in, until the system says otherwise. */");
lines.push(aliasBlock("chrome", "chrome-dark", tokens.chrome.dark));
lines.push("}");
lines.push("");

lines.push("@media (prefers-color-scheme: light) {");
lines.push("  :root {");
lines.push(aliasBlock("chrome", "chrome-light", tokens.chrome.light, "    "));
lines.push("  }");
lines.push("}");
lines.push("");

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, lines.join("\n") + "\n");
console.log(`tokens -> ${outPath}`);
