// T2's binding, wired in for real (ADVISORY-014 §1: "item 2 is missing work,
// in scope for M2, and it is this cycle's principal track"). This is the
// only file that knows `superb-core` is reached through a compiled `.wasm`
// at all -- everywhere else in this app, `EnginePort` is the whole world
// (docs/seams.md Seam 1).
//
// `src/engine/wasm-pkg/` is generated by `scripts/build-wasm.mjs`
// (`predev`/`prebuild`, gitignored) from `crates/superb-wasm`, wasm-bindgen's
// own "web" target. Vite resolves that module's `new URL("superb_wasm_bg
// .wasm", import.meta.url)` call as an ordinary asset -- no bundler plugin
// needed for wasm-bindgen's own output shape.
import init, { Engine } from "./wasm-pkg/superb_wasm.js";
import type { EnginePort, Frame, Needs, Effect, Request } from "./port";

let initialized: Promise<void> | null = null;

/** A fresh, real `superb-core` engine, running through the wasm boundary.
 *  `superb-wasm`'s own `Engine` class already carries `load`/`save`/`plan`/
 *  `decide` at the exact arity `port.d.ts` pins (`crates/superb-wasm/tests/
 *  port-dts.test.mjs`) -- this wrapper exists only to serialize the one-time
 *  wasm module instantiation behind the same async factory shape
 *  `createMockEngine` used to have, so `useEngineSession.ts`'s boot effect
 *  does not need to know which engine it is booting. */
export async function createWasmEngine(): Promise<EnginePort> {
  if (!initialized) initialized = init().then(() => undefined);
  await initialized;

  const engine = new Engine();

  // A thin object literal, not `engine` itself: `Engine`'s methods are bound
  // to its own `this` (a wasm-bindgen class instance), and passing the raw
  // instance around risks a caller assuming it's more than `EnginePort` --
  // the same reasoning `docs/seams.md` already applies to why this crate
  // exposes only these four methods and nothing else.
  return {
    load: (document: string | null) => engine.load(document),
    save: () => engine.save(),
    plan: (request: Request, nowMs: number) => engine.plan(request, nowMs) as Needs,
    decide: (request: Request, frame: Frame, nowMs: number) => engine.decide(request, frame, nowMs) as Effect[],
  };
}
